### ISSUE TITLE
Not correctly handling non-JSON yarn error

### ISSUE THREAD

**Issue by jhpedemonte** [IBM/audit-ci#45]
`audit-ci` is failing with the following error:

```
$ audit-ci --moderate --report false
undefined:1
/opt/yarn-v1.12.3/lib/cli.js:65876
^

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.proc.stderr.on.jsonl (/a/workspace/Watson-Discovery_cnc-ui_develop/node_modules/audit-ci/lib/yarn-auditer.js:76:30)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
```

It appears that yarn is failing, but `audit-ci` is trying to parse the output text as JSON, which it is not.

https://github.com/IBM/audit-ci/blob/beb57e672495af12d22031413b55d339a3a800e6/lib/yarn-auditer.js#L76

**Comment by quinnturner** [comment]
Thanks for the issue report. Are you able to share what the Yarn audit reports: `yarn audit`? It would be great to know what the Yarn error is.

Similar issues have come up in the past, notably: https://github.com/IBM/audit-ci/pull/36.

We may have to introduce a `try; catch` in the Yarn JSON-line parsing. Not sure what the expected behaviour will be if it fails.

**Comment by jhpedemonte** [comment]
This is an intermittent problem for us, but was just able to see this when running yarn locally:

```
$ yarn audit
yarn audit v1.13.0
/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:66237
            throw new (_errors || _load_errors()).ResponseError(_this3.reporter.lang('requestFailed', description), res.statusCode);
            ^

Error: Request failed "503 Service Unavailable"
    at ResponseError.ExtendableBuiltin (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:702:66)
    at new ResponseError (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:808:124)
    at Request.params.callback [as _callback] (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:66237:19)
    at Request.self.callback (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:129397:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:130369:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/pedemonte/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:130291:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
```

Agreed on `try/catch`. I think in this case it would be good for `audit-ci` to output the error from `yarn`, so user knows what the underlying error is.

**Comment by quinnturner** [comment]
Hi again,

Quite a few things have changed since this issue was opened and some changes may have fixed this issue. I am hoping you can re-test your project and see if you can reproduce with `audit-ci@^1.4.0` (newest is `1.4.1`).

Let me know if I can help.

Thanks!

**Comment by GBH** [comment]
Just want to say that I'm also experiencing similar issue. 

```
Yarn audit report summary:
Unexpected token / in JSON at position 0
Exiting...
error Command failed with exit code 1.
```

It runs fine on the second try though. Pretty annoying on the CI environment though.

It's on 1.4.1 version 🤷‍♂️

**Comment by dubbha** [comment]
Same just happened to me in 1.4.1 too

```
$ audit-ci --critical
Yarn audit report summary:
Unexpected token / in JSON at position 0
Exiting...
error Command failed with exit code 1.
```

**Comment by quinnturner** [comment]
Thanks for the heads up. This is a priority fix.

First would be to appropriately catch the error and display the message more appropriately.

This is not the first time I've seen a retry fix an audit failure. As a secondary feature, we could implement a retry mechanism if it fails unexpectedly.

**Comment by vutkin** [comment]
Any update?

**Comment by quinnturner** [comment]
PR: #66

**Comment by DylanVann** [comment]
I have had this issue on `v1.5.0`

**Comment by quinnturner** [comment]
Acknowledging that I've seen this, #76 is promising!
